name: "shyft-power"
description: | 
  Dein Energy Management System für Home Assistant. 
  
  Mit diesem Add-on kannst du deine Geräte in Home Assistant unkompliziert von shyft-power steuern lassen und so deine Stromkosten minimieren. Weitere Informationen findest du auf shyft-power.com.
version: "0.0.8.4"
slug: "shyft_addon"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
url: https://www.shyft-power.com/
options:
  shyft_access_key: "notset"
schema:
  shyft_access_key: str
ingress: true
ingress_port: 8080
panel_icon: mdi:home-lightning-bolt-outline
startup: services
boot: auto
host_network: false
hassio_api: true
homeassistant_api: true